require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'IntelliWaste' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'IntelliWasteTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end
pod 'react-native-camera', path: '../node_modules/react-native-camera'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
pod 'RNSVG', :path => '../node_modules/react-native-svg'



target 'IntelliWaste-tvOS' do
  # Pods for IntelliWaste-tvOS

  target 'IntelliWaste-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
